use customerSeg;

####### Explore Dataset #########




######### Data Cleaning ##########





##################################

######## SQL Analysis Questions ###########

# 1. What is the total revenue generated by the online retail store during the dataset period?
# 2. What is the average order value (AOV) for the online retail store?
# 3. Which country has the highest number of customers?
# 4. What are the top 5 best-selling products?
# 5. How many unique customers made purchases during the dataset period?
# 6. What is the distribution of customers based on their purchase frequency (e.g., daily, weekly, monthly)?
# 7. How many customers have not made a purchase in the last 3 months?
# 8. What is the average number of days between purchases for each customer?
# 9. Which customer has spent the most money on purchases?
# 10.What is the total quantity sold for each product category?



