USE TRANSACTIONS;

-- Spending Trends & Patterns

	-- 1. How much am I spending each month?
    SELECT ROUND(SUM(DEBIT),2) AS TOTAL_AMOUNT_SPENT, MONTH(TRANSACTION_DATE) AS MONTH FROM TRANSACTIONS
    WHERE MONTH(TRANSACTION_DATE) IS NOT NULL GROUP BY MONTH ORDER BY MONTH;
    
    -- 2. What are my peak spending days of the week?
    SELECT ROUND(SUM(DEBIT),2) AS AMOUNT_SPENT, DAYNAME(TRANSACTION_DATE) AS DAY FROM TRANSACTIONS
    WHERE DAYNAME(TRANSACTION_DATE) IS NOT NULL GROUP BY DAY ORDER BY AMOUNT_SPENT DESC;
    
    -- 3. Do I spend more on weekdays or weekends?
    SELECT ROUND(SUM(DEBIT),2) AS AMOUNT_SPENT, 
    CASE 
		 WHEN DAYNAME(TRANSACTION_DATE) IN ('Saturday', 'Sunday') THEN 'WEEKEND'
         ELSE 'WEEKDAY'
       
    END AS DAY_TYPE
    FROM TRANSACTIONS
    GROUP BY DAY_TYPE ORDER BY AMOUNT_SPENT DESC;
    
-- Category-Wise Spending

	-- 1. What are my top spending categories
	SELECT CATEGORY , ROUND(SUM(DEBIT),2) AS AMOUNT_SPENT FROM TRANSACTIONS 
    GROUP BY CATEGORY ORDER BY AMOUNT_SPENT DESC LIMIT 5;
    
    -- 2. What percentage of my total spending goes to each category?
    SELECT CATEGORY, ROUND(COUNT(*) * 100 / SUM(COUNT(*) ) OVER(),2) AS PERCENT FROM TRANSACTIONS
    GROUP BY CATEGORY ORDER BY PERCENT DESC;
    
    -- 3. How does my spending by category change over time? (Dining)
    SELECT MONTH(TRANSACTION_DATE) AS MONTH, ROUND(SUM(DEBIT),2) AS AMOUNT_SPENT FROM TRANSACTIONS
    WHERE CATEGORY = 'DINING' AND MONTH(TRANSACTION_DATE) IS NOT NULL GROUP BY MONTH ORDER BY MONTH;
    
-- High-Value & Impulse Purchases

	-- 1. What are my biggest transactions?
	SELECT * FROM TRANSACTIONS WHERE DEBIT >300 ORDER BY DESCRIPTION;

    
    